apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tanzu-dotnet-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web-basic
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-dotnet-web-app
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: ""
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        apps.tanzu.vmware.com/workload-type: web-basic
        carto.run/workload-name: tanzu-dotnet-web-app
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.health.probes.enabled="true"
        image: nitashav.azurecr.io/build-service/tanzu-dotnet-web-app-tap-dev@sha256:85046010f870688d87d678734c1f5c42d24cadf1a265e3d89e5382d90e7c520b
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

